### PR TITLE
Fix the 404 errors from December 2022

### PR DESCRIPTION
**Pull request by nowster**

### CODE REVIEW

**Comment by felipeam86** [comment]
Hi @nowster  this is solving the issue on my end, thanks!

Would you care to share how you came up with this fix? How did you identified that you needed to add the headers {"NK": "NT"} ?

Thanks

**Comment by nowster** [comment]
> Would you care to share how you came up with this fix? How did you identified that you needed to add the headers {"NK": "NT"} ?

The clue was on #90 with the mention of https://github.com/cyberjunky/python-garminconnect

In particular: https://github.com/cyberjunky/python-garminconnect/blob/master/garminconnect/__init__.py#L216 and following.

I also noticed that it's already being done here in this code: https://github.com/petergardfjall/garminexport/blob/master/garminexport/garminclient.py#L477

**Comment by 62north** [comment]
Had issues with this as well, this solved them, thanks.

**Comment by JBuitelaar** [comment]
Thanks, this also solves the problem for me. 

Btw, an easier solution is just to add this header to the session (after line 126):
```
    self.session = session_factory()           # existing line 126
    self.session.headers.update({"nk": "NT"})  # just add this
```

**Comment by JakobLichterfeld** [comment]
This solves it for me as well!

**Comment by nowster** [comment]
> Thanks, this also solves the problem for me.
> 
> Btw, an easier solution is just to add this header to the session (after line 126):
> 
> ```
>     self.session = session_factory()           # existing line 126
>     self.session.headers.update({"nk": "NT"})  # just add this
> ```

This works for me too!

**Comment by leafstrong** [comment]
Thanks for the fix. Can someone make the merge and build the code so that it can be installed via pip?

**Comment by petergardfjall** [comment]
Sorry for the delay. Have been busy with other stuff for quite some time.
I just merged commit 188e97e26ca2bac86d13fbe11d929a1cabf987f5 which is a condensed version of this PR. Credit to @nowster in the commit. Thanks for your contribution! Closing this PR.

**Pull request closed without merging**
