### PR TITLE
include CSRF-token in auth and drop 'modern' prefix in paths

### PR DESCRIPTION
**Pull request by petergardfjall**
This fix is needed to address internal changes in the Garmin API, where service
endpoints that previously worked started returning 402 responses. Appears like
dropping the `modern` prefix from the endpoint paths fixes the issue.

Also, the authentication sequence has been updated to include a CSRF (Cross-Site
Request Forgery) token to closer mimic the behavior of the login sequence on the
official web page.

### CODE REVIEW

**Comment by kfollesdal** [comment]
I close my #73 since you have come up with similar fix. See that you have changed the download urls also, I figure out that they had not changed. But I will test your PR.

**Comment by kfollesdal** [comment]
I suddenly get the following error: 
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    client.connect()
  File "/home/kristoffer/Desktop/tmp/org/garminexport/garminexport/garminclient.py", line 105, in connect
    self._authenticate()
  File "/home/kristoffer/Desktop/tmp/org/garminexport/garminexport/garminclient.py", line 126, in _authenticate
    raise ValueError("authentication failure: did you enter valid credentials?")
ValueError: authentication failure: did you enter valid credentials?
```
I get this error both with and without your PR.

The response contain the following message:
`The owner of this website (sso.garmin.com) has banned you temporarily from accessing this website.`
I will wait a bit and try again. 

It probably happened when I was testing and download same activity two times in a row.

Do you get this error?

**Comment by petergardfjall** [comment]
> The response contain the following message:
> `The owner of this website (sso.garmin.com) has banned you temporarily from accessing this website.`
> I will wait a bit and try again.
> 
> It probably happened when I was testing and download same activity two times in a row.
> 
> Do you get this error?

Yes, I also got this yesterday. Apparently Garmin (or CloudFlare) didn't appreciate my many login attempts :joy: . Wait for a while and retry.

**Comment by kfollesdal** [comment]
@petergardfjall have tested and your PR works fine :-)

**Pull request merged**
